<!-- views/scm/popen_failed.html.erb -->
<!-- called with @exception set -->
<p>
  The command:
  <pre>
    <%= h @exception.cmd.gsub(/  +/, ' ') %>
  </pre>
  failed with exit status of <%= @exception.exit_status.exitstatus %><br />
  Standard Error was:
  <pre>
  <% @exception.stderr.each do |line| -%>
    <%= h line.chomp %>
  <% end -%>
  </pre>
</p>
